# configs/loss/composite_pearson.yaml
# Composite loss with Pearson correlation loss

_target_: chipvi.training.losses.CompositeLoss
loss_functions:
  - _target_: chipvi.training.losses.nll_loss
    _partial_: true
  - _target_: chipvi.training.losses.negative_pearson_loss_wrapper
    _partial_: true
weights: [1.0, 0.1]
component_names: ["nll", "pearson"]